<?php

declare(strict_types=1);

// `config.php` IS NOT YOUR config file.
// `config.local.php` IS YOUR config file.
// Copy `config.php` to `config.local.php` then fill it with your informations.

// General
define('SITE_NAME', 'NAME OF YOUR WEBSITE');
define('SITE_URL', 'BASE DOMAIN OF YOUR WEBSITE');
define('ONION_DOMAIN', 'DOMAIN ON TOR NETWORK IF THERE IS ONE');
define('DOCUMENT_ROOT', 'DOCUMENT ROOT OF YOUR SITE (FOR EXAMPLE /var/www/html)');
define('DEV', '(TRUE IF THE SITE IS ON DEV MODE AND FALSE OTHERWISE)');

// MySQL
define('DB_STRING', 'mysql:host=localhost;dbname=YOUR_DATABASE;charset=utf8mb4');
define('DB_USER', 'YOUR DB USER');
define('DB_PSW', 'YOUR DB PASSWORD');

// SMTP
define('SMTP_HOST', 'YOUR SMTP HOST');
define('SMTP_PORT', 587);
define('SMTP_USERNAME', 'YOUR SMTP USERNAME');
define('SMTP_PSW', 'YOUR SMTP PASSWORD');
define('SMTP_MAIL', 'YOUR E-MAIL ADDRESS USE TO SEND MAILS');
define('SMTP_NAME', 'YOUR NAME USE TO SEND MAILS');

// IMAP
define('IMAP_INBOX', 'IMAP CONNECTION STRING');

// Facebook
define('FB_URL', 'YOUR FACEBOOK PAGE URL (REMOVE IF YOU DONT HAVE FACEBOOK PAGE)');
define('FB_APP_ID', 'YOUR FACEBOOK APP ID (REMOVE IF YOU DONT HAVE FACEBOOK APP)');
define('FB_APP_SECRET', 'YOUR FACEBOOK APP SECRET (REMOVE IF YOU DONT HAVE FACEBOOK APP)');
define('FB_TOKEN', 'YOUR FACEBOOK TOKEN (REMOVE IF YOU DONT HAVE FACEBOOK APP)');

// Mastodon
define('MASTO_URL', 'YOUR MASTODON ACCOUNT URL (REMOVE IF YOU DONT HAVE MASTODON ACCOUNT)');
define('MASTODON_TOKEN', 'YOUR MASTODON APP ACCESS TOKEN (REMOVE IF YOU DONT HAVE MASTODON APP)');
define('MASTODON_URL', 'YOUR MASTODON INSTANCE URL (REMOVE IF YOU DONT HAVE MASTODON APP)');
define('MASTODON_VISIBILITY', 'VISIBILITY OF TOOTS POSTED ON MASTODON (PUBLIC, PRIVATE, UNLISTED OR DIRECT) (REMOVE IF YOU DONT HAVE MASTODON APP)');
define('MASTODON_LANG', 'LANGUAGE OF TOOTS POSTED ON MASTODON (EN, FR, ZH...) (REMOVE IF YOU DONT HAVE MASTODON APP)');
define('MASTODON_MAX_LEN', 500);// Maximum length of a toot

// Git
define('GIT_DIR', 'PATH OF .GIT FOLDER');
define('GIT_URL', 'URL OF YOUR GIT REPO');
define('GIT_COMMIT_BASE_URL', 'BEGIN URL OF A COMMIT ON YOUR GIT REPO');
define('GIT_WEBHOOK_TOKEN', 'GIT WEBHOOK TOKEN TO AUTHENTIFY REPO');

// Discord
define('DISCORD_WEBHOOK_URL', 'URL OF DISCORD WEBHOOK TO POST ON YOUR SERVER (REMOVE IF YOU DONT HAVE DISCORD WEBHOOK)');

// Cesium
define('CESIUM_URL', 'YOUR CESIUM INSTANCE URL (REMOVE IF YOU DONT HAVE CESIUM INSTANCE)');

// Tickets
define('TICKETS_BOT_MAIL', 'MAIL OF TICKETS BOT MANAGER');
define('TICKETS_BOT_PSW', 'PASSWORD OF TICKETS BOT MANAGER IMAP INBOX');

// Specific to admin menu
define('WEBMAIL_URL', 'URL OF YOUR WEBMAIL (REMOVE IF YOU DONT HAVE WEBMAIL)');
define('WEBMAIL_NAME', 'NAME OF YOUR WEBMAIL (REMOVE IF YOU DONT HAVE WEBMAIL)');
define('CONTROLPANEL_URL', 'URL OF YOUR SERVER CONTROL PANEL (REMOVE IF YOU DONT HAVE CONTROL PANEL)');
define('CONTROLPANEL_NAME', 'NAME OF YOUR SERVER CONTROL PANEL (REMOVE IF YOU DONT HAVE CONTROL PANEL)');

// Captcha
define('MTCAPTCHA_PUBLIC', 'Your MtCaptcha public key');
define('MTCAPTCHA_PRIVATE', 'Your MtCaptcha private key');
